### ISSUE TITLE
ERROR:  Invalid version of dependency, need 'spdlog' ['>=1.3.1'] found '1.2.0'.

### ISSUE THREAD

**Issue by cryptix** [colemickens/nixpkgs-wayland#150]
Hey! I just tried latest master but ran into this:

```
...
Downloading spdlog source from https://github.com/gabime/spdlog/archive/v1.3.1.tar.gz
Couldn't use fallback subproject in subprojects/spdlog for the dependency spdlog
Reason: Traceback (most recent call last):
  File "/nix/store/dwi186iqm6p3kfncfsl62fbfwfry1yci-python3-3.7.3/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/nix/store/dwi186iqm6p3kfncfsl62fbfwfry1yci-python3-3.7.3/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/nix/store/dwi186iqm6p3kfncfsl62fbfwfry1yci-python3-3.7.3/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/nix/store/dwi186iqm6p3kfncfsl62fbfwfry1yci-python3-3.7.3/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/nix/store/dwi186iqm6p3kfncfsl62fbfwfry1yci-python3-3.7.3/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/nix/store/dwi186iqm6p3kfncfsl62fbfwfry1yci-python3-3.7.3/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/nix/store/dwi186iqm6p3kfncfsl62fbfwfry1yci-python3-3.7.3/lib/python3.7/http/client.py", line 1384, in connect
    super().connect()
  File "/nix/store/dwi186iqm6p3kfncfsl62fbfwfry1yci-python3-3.7.3/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/nix/store/dwi186iqm6p3kfncfsl62fbfwfry1yci-python3-3.7.3/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/nix/store/dwi186iqm6p3kfncfsl62fbfwfry1yci-python3-3.7.3/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/bblx1dvp2zh4dzkdbcqcgndxyvy7ydc7-meson-0.49.1/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 3097, in dependency_fallback
    self.do_subproject(dirname, sp_kwargs)
  File "/nix/store/bblx1dvp2zh4dzkdbcqcgndxyvy7ydc7-meson-0.49.1/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 2315, in do_subproject
    resolved = r.resolve(dirname)
  File "/nix/store/bblx1dvp2zh4dzkdbcqcgndxyvy7ydc7-meson-0.49.1/lib/python3.7/site-packages/mesonbuild/wrap/wrap.py", line 144, in resolve
    self.get_file()
  File "/nix/store/bblx1dvp2zh4dzkdbcqcgndxyvy7ydc7-meson-0.49.1/lib/python3.7/site-packages/mesonbuild/wrap/wrap.py", line 208, in get_file
    path = self.get_file_internal('source')
  File "/nix/store/bblx1dvp2zh4dzkdbcqcgndxyvy7ydc7-meson-0.49.1/lib/python3.7/site-packages/mesonbuild/wrap/wrap.py", line 326, in get_file_internal
    self.download(what, cache_path)
  File "/nix/store/bblx1dvp2zh4dzkdbcqcgndxyvy7ydc7-meson-0.49.1/lib/python3.7/site-packages/mesonbuild/wrap/wrap.py", line 308, in download
    dhash, tmpfile = self.get_data(srcurl)
  File "/nix/store/bblx1dvp2zh4dzkdbcqcgndxyvy7ydc7-meson-0.49.1/lib/python3.7/site-packages/mesonbuild/wrap/wrap.py", line 258, in get_data
    resp = urllib.request.urlopen(url, timeout=req_timeout)
  File "/nix/store/dwi186iqm6p3kfncfsl62fbfwfry1yci-python3-3.7.3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/nix/store/dwi186iqm6p3kfncfsl62fbfwfry1yci-python3-3.7.3/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/nix/store/dwi186iqm6p3kfncfsl62fbfwfry1yci-python3-3.7.3/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/nix/store/dwi186iqm6p3kfncfsl62fbfwfry1yci-python3-3.7.3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/nix/store/dwi186iqm6p3kfncfsl62fbfwfry1yci-python3-3.7.3/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/nix/store/dwi186iqm6p3kfncfsl62fbfwfry1yci-python3-3.7.3/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>


meson.build:51:0: ERROR:  Invalid version of dependency, need 'spdlog' ['>=1.3.1'] found '1.2.0'.

A full log can be found at /build/source/build/meson-logs/meson-log.txt
builder for '/nix/store/b7phmyx2pq0xdaxgfdyid0fx1jysbb39-waybar-1962caf144ebd1d8772ffa0b77630ea48e61e615.drv' failed with exit code 1
```

Before my last pull there was a `pkgs-tmp/spdlog` that was working fine after I patched it myself (before finding https://github.com/NixOS/nixpkgs/pull/62057 ... :sweat_smile: - my last branch is [here](https://github.com/colemickens/nixpkgs-wayland/compare/master...cryptix:mine)). I will try to backport that, just wanted to ask what's the intended way forward here or if you have an idea what went wrong when I tried to build this. I guess since the above is merged it should show up in unstable eventually? I'm still fuzzy on when nixpkgs master becomes nixos unstable..

ps: I've been using this overlay for the last month for my daily work and it's quite the blessing. Plus I learned a lot about overlays in nixos. Thanks a ton for putting this together!

**Comment by colemickens** [comment]
Hi @cryptix, the way that `update.sh` and `build.nix` work means that this repo is only tested and expected to work against `nixos-unstable` and `nixpkgs-stable`. I only push when the `update.sh` script is able to read cleanly.

Sometimes I do some workarounds, like providing spdlog, and overriding the versions of wlroots (I'm actually doing that now for a round of updates and remembered this issue), but I prefer to undo them as soon as possible.

For nixos-unstable, spdlog was bumped 13 days ago, as the channel is currently at this rev: https://github.com/NixOS/nixpkgs-channels/tree/1dc26c32edffdb73adb0a82b430834d3404aa8f3/pkgs/development/libraries/spdlog

For nixpkgs-unstable, similar situation: https://github.com/NixOS/nixpkgs-channels/tree/61f0936d1cd73760312712615233cd80195a9b47/pkgs/development/libraries/spdlog

If you're on a different nixpkgs revision and it's been working, you've mostly been getting lucky. If you want, you could potentially try to see how hard it is to support whatever you're on. Otherwise, update nixpkgs more often. :)

**Comment by colemickens** [comment]
Sorry, I need to revise- my last comment is misleading, as those are the commit dates, not the dates they were available on those channels. And I don't know a fast way to look that up specifically, though this is one of my favorite things: https://howoldis.herokuapp.com.

I can maybe prove it by explaining the update process, maybe it'll be interesting to you or someone else:

1. It updates the `nixpkgs/<channel>/metadata.nix` to point at the commit for the tip of those channels.

2. It updates the `pkgs/<package>/metadata.nix` package for all packages on GitHub.

3. It builds `build.nix -A nixosUnstable` and `nixpkgsUnstable`. It specifically builds them with `NIX_PATH` unset, with the nixpkgs that are directly referenced in `nixpkgs/<channel>/metadata.nix`.

This means that anyone with Nix should be able to run `./update.sh` from this repo and get the same expressions every time. (Barring some changes in `nixpkgs.config` and other overlays, and other stuff that I don't know about, probably.)

And let me resummarize my advice as well:

1. Be on `nixos-unstable` or `nixpkgs-unstable` and be up-to-date.

2. Pin the revision you're using of `nixpkgs-wayland`, and update it when you update your nixpkgs channel.

3. Try to contribute to this overlay to support all three channels at once (not really sure how realistic this is, I've never used a stable channel)

**Comment by colemickens** [comment]
Also, I guess if I take too long to update this, and you update ahead of me, you can end up moving to a revision of something that is too new. (though it doesn't sound like that's the case you're hitting)

**Comment by cryptix** [comment]
Thanks, this was very insightful! Let me recap a gist to see if I grokked that correctly: You are using nixos-unstable as the base for your whole OS, right?

I have been using stable release as my base system channel and unstable just for my user env. I was under the impression that the unstable that is importet by the overlay just supplies _the more recent versions for packages inside the overlay that need them_?

That being said, I'm totally fine with manually updating and seeing if `nixos-rebuild test` works before switching.. I mean this is where nix really shines anyway :)

**Comment by colemickens** [comment]
Closing since it seems like this isn't an active issue.
